### ISSUE TITLE
An error occurred: Authorization failed. Please supply a valid authentication key.

### ISSUE THREAD

**Issue by CodingMadness** [lecode-official/deepl-dotnet#10]
Title.

And the Key is 1-1 copied from my account, I only start to ponder about the possibillity that their Servers have some issues, it looks iffy to me when I try to see some pricing stuff on my account, it doesnt load properly and stuff like that?

Does any1 know what this can be??

Thx and 

Best regards

Shpendicus

**Comment by lecode-official** [comment]
Hi Shpendicus,

I am really sorry for only answering now. Did you find anything out so far? The only two things that I can think of from the top of my head are:

1. As you said, there was an error provisioning your account, in that case, please contact the customer service of DeepL
2. Are you using a free or a pro account. If you are using a free account, then you have to specify that in the constructor of the `DeepLClient`

Please let me know if you figured out what the problem was. If not, then it would be nice if you could send some more information (code, stack trace, etc.).

Best regards
David

**Comment by lecode-official** [comment]
Hi Shpendicus,

were you able to fix your problem?

**Comment by YouGina** [comment]
When you use an older .net version you need to add this to your code:
```C#
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
```
Or it can be added to the library

**Comment by lecode-official** [comment]
It seems like this is [bad practice](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5386) to hard-code the security protocol version. Unless there are some really good reasons to do this, I would like to avoid hard-coding it.

Since there has been little activity in this issue in the past few weeks, I will close it for now. If the issue persists, please reopen with more relevant information.
