### ISSUE TITLE
Add the new supported languages.

### ISSUE THREAD

**Issue by vandebeer** [lecode-official/deepl-dotnet#3]
Hi, I would like to add the new supported languages. can I do it or is it already planned?

https://www.deepl.com/docs-api/translating-text/request/

**Comment by lecode-official** [comment]
It looks like they have added a couple of new languages since the last time I have updated the list of supported languages. I would very much appreciate if you would update the languages. Just a few pointers:

- You'll have to update the `Language` enumeration: https://github.com/lecode-official/deepl-dotnet/blob/master/source/DeepL/Language.cs
- You'll have to update the translation between `Language` and language code: https://github.com/lecode-official/deepl-dotnet/blob/master/source/DeepL/DeepLClient.cs#L78
- Don't forget to update the documentation: https://github.com/lecode-official/deepl-dotnet/blob/master/documentation/translating-text.md#languages
- Don't forget to add yourself to the contributors list: https://github.com/lecode-official/deepl-dotnet/blob/master/CONTRIBUTORS.md

I believe this is everything that has to be done in order to update the language. If you have any more questions, then feel free to reach out to me.

**Comment by vandebeer** [comment]
Thanks for your reply, i have created a pull request and close this issue

**Comment by lecode-official** [comment]
I have just uploaded a new version of DeepL.NET to NuGet. It is still being indexed, but should be available shortly as version 0.2.0.

**Comment by vandebeer** [comment]
Just did the update on our system. Thanks again for the quick implementation.
