### ISSUE TITLE
NullReferenceException in constructor

### ISSUE THREAD

**Issue by jcmag** [lecode-official/deepl-dotnet#6]
Hi,

I'm calling DeepLClient from a web application, and the constructor returns a NullReferenceException on this line:

`this.httpClient.DefaultRequestHeaders.Add("User-Agent", $"DeepL.NET/{Assembly.GetEntryAssembly().GetName().Version}");`

I've replaced GetEntryAssembly() with GetExecutingAssembly() and it works now

**Comment by lecode-official** [comment]
Hi @jcmag,

thank you for opening the issue. It is weird that you are getting a `NullReferenceException`. But, as I see this, I should have used `GetExecutingAssembly` from begin with, anyway. `GetEntryAssembly` gets the first assembly in the application domain, i.e. is (or should be) your application, while `GetExecutingAssembly` gets the assembly whose code is currently being executed, i.e. DeepL.NET. Since I want the version of DeepL ist does not make much sense that I have used `GetEntryAssembly`. I will push an update soon. I will add you to the contributors list, unless you do not want to.

**Comment by jcmag** [comment]
ok, and thanks for your library, it's very useful 👍 
(you can add me to the contributors ;) )

**Comment by lecode-official** [comment]
I have just published a new NuGet package with the fix.

**Comment by jcmag** [comment]
> 
> 
> I have just published a new NuGet package with the fix.

perfect, thanks!
